//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *APIHealthStatus) DeepCopyInto(out *APIHealthStatus) { *out = *in }
func (in *APIHealthStatus) DeepCopy() *APIHealthStatus { if in == nil { return nil }; out := new(APIHealthStatus); in.DeepCopyInto(out); return out }
func (in *AvtoVAZ) DeepCopyInto(out *AvtoVAZ) { *out = *in; out.TypeMeta = in.TypeMeta; in.ObjectMeta.DeepCopyInto(&out.ObjectMeta); in.Spec.DeepCopyInto(&out.Spec); in.Status.DeepCopyInto(&out.Status) }
func (in *AvtoVAZ) DeepCopy() *AvtoVAZ { if in == nil { return nil }; out := new(AvtoVAZ); in.DeepCopyInto(out); return out }
func (in *AvtoVAZ) DeepCopyObject() runtime.Object { if c := in.DeepCopy(); c != nil { return c }; return nil }
func (in *AvtoVAZCapacityPolicy) DeepCopyInto(out *AvtoVAZCapacityPolicy) { *out = *in }
func (in *AvtoVAZCapacityPolicy) DeepCopy() *AvtoVAZCapacityPolicy { if in == nil { return nil }; out := new(AvtoVAZCapacityPolicy); in.DeepCopyInto(out); return out }
func (in *AvtoVAZDefaultsSpec) DeepCopyInto(out *AvtoVAZDefaultsSpec) { *out = *in }
func (in *AvtoVAZDefaultsSpec) DeepCopy() *AvtoVAZDefaultsSpec { if in == nil { return nil }; out := new(AvtoVAZDefaultsSpec); in.DeepCopyInto(out); return out }
func (in *AvtoVAZFridayPolicy) DeepCopyInto(out *AvtoVAZFridayPolicy) { *out = *in }
func (in *AvtoVAZFridayPolicy) DeepCopy() *AvtoVAZFridayPolicy { if in == nil { return nil }; out := new(AvtoVAZFridayPolicy); in.DeepCopyInto(out); return out }
func (in *AvtoVAZList) DeepCopyInto(out *AvtoVAZList) { *out = *in; out.TypeMeta = in.TypeMeta; in.ListMeta.DeepCopyInto(&out.ListMeta); if in.Items != nil { in, out := &in.Items, &out.Items; *out = make([]AvtoVAZ, len(*in)); for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) } } }
func (in *AvtoVAZList) DeepCopy() *AvtoVAZList { if in == nil { return nil }; out := new(AvtoVAZList); in.DeepCopyInto(out); return out }
func (in *AvtoVAZList) DeepCopyObject() runtime.Object { if c := in.DeepCopy(); c != nil { return c }; return nil }
func (in *AvtoVAZQualityPolicy) DeepCopyInto(out *AvtoVAZQualityPolicy) { *out = *in }
func (in *AvtoVAZQualityPolicy) DeepCopy() *AvtoVAZQualityPolicy { if in == nil { return nil }; out := new(AvtoVAZQualityPolicy); in.DeepCopyInto(out); return out }
func (in *AvtoVAZRolloutPolicy) DeepCopyInto(out *AvtoVAZRolloutPolicy) { *out = *in }
func (in *AvtoVAZRolloutPolicy) DeepCopy() *AvtoVAZRolloutPolicy { if in == nil { return nil }; out := new(AvtoVAZRolloutPolicy); in.DeepCopyInto(out); return out }
func (in *AvtoVAZSafetyPolicy) DeepCopyInto(out *AvtoVAZSafetyPolicy) { *out = *in }
func (in *AvtoVAZSafetyPolicy) DeepCopy() *AvtoVAZSafetyPolicy { if in == nil { return nil }; out := new(AvtoVAZSafetyPolicy); in.DeepCopyInto(out); return out }
func (in *AvtoVAZSpec) DeepCopyInto(out *AvtoVAZSpec) { *out = *in }
func (in *AvtoVAZSpec) DeepCopy() *AvtoVAZSpec { if in == nil { return nil }; out := new(AvtoVAZSpec); in.DeepCopyInto(out); return out }
func (in *AvtoVAZStatus) DeepCopyInto(out *AvtoVAZStatus) { *out = *in; if in.Conditions != nil { in, out := &in.Conditions, &out.Conditions; *out = make([]metav1.Condition, len(*in)); for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) } } }
func (in *AvtoVAZStatus) DeepCopy() *AvtoVAZStatus { if in == nil { return nil }; out := new(AvtoVAZStatus); in.DeepCopyInto(out); return out }
func (in *BrunerApp) DeepCopyInto(out *BrunerApp) { *out = *in; out.TypeMeta = in.TypeMeta; in.ObjectMeta.DeepCopyInto(&out.ObjectMeta); in.Spec.DeepCopyInto(&out.Spec); in.Status.DeepCopyInto(&out.Status) }
func (in *BrunerApp) DeepCopy() *BrunerApp { if in == nil { return nil }; out := new(BrunerApp); in.DeepCopyInto(out); return out }
func (in *BrunerApp) DeepCopyObject() runtime.Object { if c := in.DeepCopy(); c != nil { return c }; return nil }
func (in *BrunerAppDeploymentStatus) DeepCopyInto(out *BrunerAppDeploymentStatus) { *out = *in }
func (in *BrunerAppDeploymentStatus) DeepCopy() *BrunerAppDeploymentStatus { if in == nil { return nil }; out := new(BrunerAppDeploymentStatus); in.DeepCopyInto(out); return out }
func (in *BrunerAppEndpointStatus) DeepCopyInto(out *BrunerAppEndpointStatus) { *out = *in; if in.LastVerifiedAt != nil { in, out := &in.LastVerifiedAt, &out.LastVerifiedAt; *out = (*in).DeepCopy() } }
func (in *BrunerAppEndpointStatus) DeepCopy() *BrunerAppEndpointStatus { if in == nil { return nil }; out := new(BrunerAppEndpointStatus); in.DeepCopyInto(out); return out }
func (in *BrunerAppExposureSpec) DeepCopyInto(out *BrunerAppExposureSpec) { *out = *in }
func (in *BrunerAppExposureSpec) DeepCopy() *BrunerAppExposureSpec { if in == nil { return nil }; out := new(BrunerAppExposureSpec); in.DeepCopyInto(out); return out }
func (in *BrunerAppHealthSpec) DeepCopyInto(out *BrunerAppHealthSpec) { *out = *in }
func (in *BrunerAppHealthSpec) DeepCopy() *BrunerAppHealthSpec { if in == nil { return nil }; out := new(BrunerAppHealthSpec); in.DeepCopyInto(out); return out }
func (in *BrunerAppImageStatus) DeepCopyInto(out *BrunerAppImageStatus) { *out = *in }
func (in *BrunerAppImageStatus) DeepCopy() *BrunerAppImageStatus { if in == nil { return nil }; out := new(BrunerAppImageStatus); in.DeepCopyInto(out); return out }
func (in *BrunerAppList) DeepCopyInto(out *BrunerAppList) { *out = *in; out.TypeMeta = in.TypeMeta; in.ListMeta.DeepCopyInto(&out.ListMeta); if in.Items != nil { in, out := &in.Items, &out.Items; *out = make([]BrunerApp, len(*in)); for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) } } }
func (in *BrunerAppList) DeepCopy() *BrunerAppList { if in == nil { return nil }; out := new(BrunerAppList); in.DeepCopyInto(out); return out }
func (in *BrunerAppList) DeepCopyObject() runtime.Object { if c := in.DeepCopy(); c != nil { return c }; return nil }
func (in *BrunerAppRolloutSpec) DeepCopyInto(out *BrunerAppRolloutSpec) { *out = *in }
func (in *BrunerAppRolloutSpec) DeepCopy() *BrunerAppRolloutSpec { if in == nil { return nil }; out := new(BrunerAppRolloutSpec); in.DeepCopyInto(out); return out }
func (in *BrunerAppServiceStatus) DeepCopyInto(out *BrunerAppServiceStatus) { *out = *in }
func (in *BrunerAppServiceStatus) DeepCopy() *BrunerAppServiceStatus { if in == nil { return nil }; out := new(BrunerAppServiceStatus); in.DeepCopyInto(out); return out }
func (in *BrunerAppSpec) DeepCopyInto(out *BrunerAppSpec) { *out = *in; in.Resources.DeepCopyInto(&out.Resources); if in.ImagePullSecrets != nil { in, out := &in.ImagePullSecrets, &out.ImagePullSecrets; *out = make([]corev1.LocalObjectReference, len(*in)); copy(*out, *in) } }
func (in *BrunerAppSpec) DeepCopy() *BrunerAppSpec { if in == nil { return nil }; out := new(BrunerAppSpec); in.DeepCopyInto(out); return out }
func (in *BrunerAppStatus) DeepCopyInto(out *BrunerAppStatus) { *out = *in; in.Endpoint.DeepCopyInto(&out.Endpoint); if in.Conditions != nil { in, out := &in.Conditions, &out.Conditions; *out = make([]metav1.Condition, len(*in)); for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) } } }
func (in *BrunerAppStatus) DeepCopy() *BrunerAppStatus { if in == nil { return nil }; out := new(BrunerAppStatus); in.DeepCopyInto(out); return out }
func (in *CNIHealthStatus) DeepCopyInto(out *CNIHealthStatus) { *out = *in }
func (in *CNIHealthStatus) DeepCopy() *CNIHealthStatus { if in == nil { return nil }; out := new(CNIHealthStatus); in.DeepCopyInto(out); return out }
func (in *EndpointCapabilityStatus) DeepCopyInto(out *EndpointCapabilityStatus) { *out = *in; if in.AvailablePorts != nil { in, out := &in.AvailablePorts, &out.AvailablePorts; *out = make([]int32, len(*in)); copy(*out, *in) } }
func (in *EndpointCapabilityStatus) DeepCopy() *EndpointCapabilityStatus { if in == nil { return nil }; out := new(EndpointCapabilityStatus); in.DeepCopyInto(out); return out }
func (in *FactoryResourcesStatus) DeepCopyInto(out *FactoryResourcesStatus) { *out = *in }
func (in *FactoryResourcesStatus) DeepCopy() *FactoryResourcesStatus { if in == nil { return nil }; out := new(FactoryResourcesStatus); in.DeepCopyInto(out); return out }
func (in *GatewayPortRange) DeepCopyInto(out *GatewayPortRange) { *out = *in }
func (in *GatewayPortRange) DeepCopy() *GatewayPortRange { if in == nil { return nil }; out := new(GatewayPortRange); in.DeepCopyInto(out); return out }
func (in *Konveer) DeepCopyInto(out *Konveer) { *out = *in; out.TypeMeta = in.TypeMeta; in.ObjectMeta.DeepCopyInto(&out.ObjectMeta); in.Spec.DeepCopyInto(&out.Spec); in.Status.DeepCopyInto(&out.Status) }
func (in *Konveer) DeepCopy() *Konveer { if in == nil { return nil }; out := new(Konveer); in.DeepCopyInto(out); return out }
func (in *Konveer) DeepCopyObject() runtime.Object { if c := in.DeepCopy(); c != nil { return c }; return nil }
func (in *KonveerAppReference) DeepCopyInto(out *KonveerAppReference) { *out = *in }
func (in *KonveerAppReference) DeepCopy() *KonveerAppReference { if in == nil { return nil }; out := new(KonveerAppReference); in.DeepCopyInto(out); return out }
func (in *KonveerChecksSpec) DeepCopyInto(out *KonveerChecksSpec) { *out = *in }
func (in *KonveerChecksSpec) DeepCopy() *KonveerChecksSpec { if in == nil { return nil }; out := new(KonveerChecksSpec); in.DeepCopyInto(out); return out }
func (in *KonveerChecksStatus) DeepCopyInto(out *KonveerChecksStatus) { *out = *in }
func (in *KonveerChecksStatus) DeepCopy() *KonveerChecksStatus { if in == nil { return nil }; out := new(KonveerChecksStatus); in.DeepCopyInto(out); return out }
func (in *KonveerEndpointStatus) DeepCopyInto(out *KonveerEndpointStatus) { *out = *in }
func (in *KonveerEndpointStatus) DeepCopy() *KonveerEndpointStatus { if in == nil { return nil }; out := new(KonveerEndpointStatus); in.DeepCopyInto(out); return out }
func (in *KonveerList) DeepCopyInto(out *KonveerList) { *out = *in; out.TypeMeta = in.TypeMeta; in.ListMeta.DeepCopyInto(&out.ListMeta); if in.Items != nil { in, out := &in.Items, &out.Items; *out = make([]Konveer, len(*in)); for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) } } }
func (in *KonveerList) DeepCopy() *KonveerList { if in == nil { return nil }; out := new(KonveerList); in.DeepCopyInto(out); return out }
func (in *KonveerList) DeepCopyObject() runtime.Object { if c := in.DeepCopy(); c != nil { return c }; return nil }
func (in *KonveerObservedAppReference) DeepCopyInto(out *KonveerObservedAppReference) { *out = *in }
func (in *KonveerObservedAppReference) DeepCopy() *KonveerObservedAppReference { if in == nil { return nil }; out := new(KonveerObservedAppReference); in.DeepCopyInto(out); return out }
func (in *KonveerRolloutStatus) DeepCopyInto(out *KonveerRolloutStatus) { *out = *in; if in.StartedAt != nil { in, out := &in.StartedAt, &out.StartedAt; *out = (*in).DeepCopy() }; if in.CompletedAt != nil { in, out := &in.CompletedAt, &out.CompletedAt; *out = (*in).DeepCopy() } }
func (in *KonveerRolloutStatus) DeepCopy() *KonveerRolloutStatus { if in == nil { return nil }; out := new(KonveerRolloutStatus); in.DeepCopyInto(out); return out }
func (in *KonveerSpec) DeepCopyInto(out *KonveerSpec) { *out = *in }
func (in *KonveerSpec) DeepCopy() *KonveerSpec { if in == nil { return nil }; out := new(KonveerSpec); in.DeepCopyInto(out); return out }
func (in *KonveerStatus) DeepCopyInto(out *KonveerStatus) { *out = *in; in.Rollout.DeepCopyInto(&out.Rollout); if in.Conditions != nil { in, out := &in.Conditions, &out.Conditions; *out = make([]metav1.Condition, len(*in)); for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) } } }
func (in *KonveerStatus) DeepCopy() *KonveerStatus { if in == nil { return nil }; out := new(KonveerStatus); in.DeepCopyInto(out); return out }
func (in *NodeHealthStatus) DeepCopyInto(out *NodeHealthStatus) { *out = *in; if in.Allocatable != nil { in, out := &in.Allocatable, &out.Allocatable; *out = make(map[string]string, len(*in)); for key, val := range *in { (*out)[key] = val } } }
func (in *NodeHealthStatus) DeepCopy() *NodeHealthStatus { if in == nil { return nil }; out := new(NodeHealthStatus); in.DeepCopyInto(out); return out }
func (in *RuntimeHealthStatus) DeepCopyInto(out *RuntimeHealthStatus) { *out = *in }
func (in *RuntimeHealthStatus) DeepCopy() *RuntimeHealthStatus { if in == nil { return nil }; out := new(RuntimeHealthStatus); in.DeepCopyInto(out); return out }
func (in *Togliatti) DeepCopyInto(out *Togliatti) { *out = *in; out.TypeMeta = in.TypeMeta; in.ObjectMeta.DeepCopyInto(&out.ObjectMeta); in.Spec.DeepCopyInto(&out.Spec); in.Status.DeepCopyInto(&out.Status) }
func (in *Togliatti) DeepCopy() *Togliatti { if in == nil { return nil }; out := new(Togliatti); in.DeepCopyInto(out); return out }
func (in *Togliatti) DeepCopyObject() runtime.Object { if c := in.DeepCopy(); c != nil { return c }; return nil }
func (in *TogliattiCapacityProfiles) DeepCopyInto(out *TogliattiCapacityProfiles) { *out = *in; if in.Available != nil { in, out := &in.Available, &out.Available; *out = make([]BrunerProfile, len(*in)); copy(*out, *in) } }
func (in *TogliattiCapacityProfiles) DeepCopy() *TogliattiCapacityProfiles { if in == nil { return nil }; out := new(TogliattiCapacityProfiles); in.DeepCopyInto(out); return out }
func (in *TogliattiDiagnosticsSpec) DeepCopyInto(out *TogliattiDiagnosticsSpec) { *out = *in }
func (in *TogliattiDiagnosticsSpec) DeepCopy() *TogliattiDiagnosticsSpec { if in == nil { return nil }; out := new(TogliattiDiagnosticsSpec); in.DeepCopyInto(out); return out }
func (in *TogliattiEndpointSpec) DeepCopyInto(out *TogliattiEndpointSpec) { *out = *in }
func (in *TogliattiEndpointSpec) DeepCopy() *TogliattiEndpointSpec { if in == nil { return nil }; out := new(TogliattiEndpointSpec); in.DeepCopyInto(out); return out }
func (in *TogliattiList) DeepCopyInto(out *TogliattiList) { *out = *in; out.TypeMeta = in.TypeMeta; in.ListMeta.DeepCopyInto(&out.ListMeta); if in.Items != nil { in, out := &in.Items, &out.Items; *out = make([]Togliatti, len(*in)); for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) } } }
func (in *TogliattiList) DeepCopy() *TogliattiList { if in == nil { return nil }; out := new(TogliattiList); in.DeepCopyInto(out); return out }
func (in *TogliattiList) DeepCopyObject() runtime.Object { if c := in.DeepCopy(); c != nil { return c }; return nil }
func (in *TogliattiSpec) DeepCopyInto(out *TogliattiSpec) { *out = *in; in.CapacityProfiles.DeepCopyInto(&out.CapacityProfiles) }
func (in *TogliattiSpec) DeepCopy() *TogliattiSpec { if in == nil { return nil }; out := new(TogliattiSpec); in.DeepCopyInto(out); return out }
func (in *TogliattiStatus) DeepCopyInto(out *TogliattiStatus) { *out = *in; in.Node.DeepCopyInto(&out.Node); in.Endpoint.DeepCopyInto(&out.Endpoint); if in.Conditions != nil { in, out := &in.Conditions, &out.Conditions; *out = make([]metav1.Condition, len(*in)); for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) } } }
func (in *TogliattiStatus) DeepCopy() *TogliattiStatus { if in == nil { return nil }; out := new(TogliattiStatus); in.DeepCopyInto(out); return out }
